import styles from "./page.module.scss"

const showPage = false

import { Metadata } from "next"

export const metadata: Metadata = {
    title: "Terms Policy",
    description: ""
}

export default function Terms() {

    if (!showPage) {
        return <p>Unavailoble page</p>
    }
    /*
    return (
    <div className="font-sans flex flex-col items-center justify-items-center  p-2.5 pb-2.5 pt-[75px] sm:p-20">
        <h1 className={styles.title}>TERMS & CONDITIONS</h1>

        <h2 className={styles.heading}>GENERAL TERMS</h2>
        <p className={styles.paragraph}>
        BY ACCESSING AND PLACING AN ORDER WITH VELOUR GARMENTS, YOU CONFIRM THAT YOU ARE IN AGREEMENT WITH AND BOUND BY THE TERMS OF SERVICE CONTAINED IN THE TERMS & CONDITIONS OUTLINED BELOW. THESE TERMS APPLY TO THE ENTIRE WEBSITE AND ANY EMAIL OR OTHER TYPE OF COMMUNICATION BETWEEN YOU AND VELOUR GARMENTS.
        </p>
        <p className={styles.paragraph}>
        UNDER NO CIRCUMSTANCES SHALL VELOUR GARMENTS TEAM BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES, INCLUDING, BUT NOT LIMITED TO, LOSS OF DATA OR PROFIT, ARISING OUT OF THE USE, OR THE INABILITY TO USE, THE MATERIALS ON THIS SITE, EVEN IF VELOUR GARMENTS TEAM OR AN AUTHORIZED REPRESENTATIVE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IF YOUR USE OF MATERIALS FROM THIS SITE RESULTS IN THE NEED FOR SERVICING, REPAIR OR CORRECTION OF EQUIPMENT OR DATA, YOU ASSUME ANY COSTS THEREOF.
        </p>
        <p className={styles.paragraph}>
        VELOUR GARMENTS WILL NOT BE RESPONSIBLE FOR ANY OUTCOME THAT MAY OCCUR DURING THE COURSE OF USAGE OF OUR RESOURCES. WE RESERVE THE RIGHTS TO CHANGE PRICES AND REVISE THE RESOURCES USAGE POLICY IN ANY MOMENT.
        </p>

        <h2 className={styles.heading}>LICENSE</h2>
        <p className={styles.paragraph}>
        VELOUR GARMENTS GRANTS YOU A REVOCABLE, NON-EXCLUSIVE, NON-TRANSFERABLE, LIMITED LICENSE TO DOWNLOAD, INSTALL AND USE THE WEBSITE STRICTLY IN ACCORDANCE WITH THE TERMS OF THIS AGREEMENT.
        </p>
        <p className={styles.paragraph}>
        THESE TERMS & CONDITIONS ARE A CONTRACT BETWEEN YOU AND VELOUR GARMENTS (REFERRED TO IN THESE TERMS & CONDITIONS AS "VELOUR GARMENTS", "US", "WE" OR "OUR"), THE PROVIDER OF THE VELOUR GARMENTS WEBSITE AND THE SERVICES ACCESSIBLE FROM THE VELOUR GARMENTS WEBSITE (WHICH ARE COLLECTIVELY REFERRED TO IN THESE TERMS & CONDITIONS AS THE "VELOUR GARMENTS SERVICE").
        </p>

        <h2 className={styles.heading}>RESTRICTIONS</h2>
        <ul className={styles.list}>
        <li>LICENSE, SELL, RENT, LEASE, ASSIGN, DISTRIBUTE, TRANSMIT, HOST, OUTSOURCE, DISCLOSE OR OTHERWISE COMMERCIALLY EXPLOIT THE WEBSITE OR MAKE THE PLATFORM AVAILABLE TO ANY THIRD PARTY.</li>
        <li>MODIFY, MAKE DERIVATIVE WORKS OF, DISASSEMBLE, DECRYPT, REVERSE COMPILE OR REVERSE ENGINEER ANY PART OF THE WEBSITE.</li>
        <li>REMOVE, ALTER OR OBSCURE ANY PROPRIETARY NOTICE (INCLUDING ANY NOTICE OF COPYRIGHT OR TRADEMARK) OF VELOUR GARMENTS OR ITS AFFILIATES, PARTNERS, SUPPLIERS OR THE LICENSORS OF THE WEBSITE.</li>
        </ul>

        <h2 className={styles.heading}>RETURN AND REFUND POLICY</h2>
        <p className={styles.paragraph}>
        THANKS FOR SHOPPING AT VELOUR GARMENTS. WE APPRECIATE THE FACT THAT YOU LIKE TO BUY THE STUFF WE BUILD. WE ALSO WANT TO MAKE SURE YOU HAVE A REWARDING EXPERIENCE WHILE YOU’RE EXPLORING, EVALUATING, AND PURCHASING OUR PRODUCTS.
        </p>
        <p className={styles.paragraph}>
        IF, FOR ANY REASON, YOU ARE NOT COMPLETELY SATISFIED WITH ANY GOOD OR SERVICE THAT WE PROVIDE, DON'T HESITATE TO CONTACT US AND WE WILL DISCUSS ANY OF THE ISSUES YOU ARE GOING THROUGH WITH OUR PRODUCT THROUGH SUPPORT@VELOURGARMENTS.COM
        </p>
        <h2 className={styles.heading}>CONTACT</h2>
        <ul className={styles.list}>
        <li>VIA EMAIL: SUPPORT@VELOURGARMENTS.COM</li>
        </ul>
        <p className={styles.paragraph}>VELOUR GARMENTS SL</p>
        <p className={styles.paragraph}>B10517902</p>
    </div>
    )
    */
}