import styles from "./page.module.scss"

const showPage = false

export default function Products() {
  if (!showPage) {
    return <p>Unavailoble page</p>
}
/*
    return (
    <div className="font-sans flex flex-col items-center justify-items-center  p-2.5 pb-2.5 pt-[75px] sm:p-20">
              <h1 className={styles.heading}>SHIPPING</h1>

<p className={styles.paragraph}>
  PLEASE ALLOW 1-5 (BUSINESS DAYS) FOR OUR WAREHOUSE TEAM TO PROCESS AND
  DISPATCH EVERY ORDER FROM OUR RETAIL STORE. ONCE SHIPPED, THE PACKAGE
  WILL BE DELIVERED WITHIN 24-72 HOURS AFTER FULFILLMENT.
</p>
<p className={styles.paragraph}>
  PRE-ORDERS MIGHT TAKE UP TO 5-8 WEEKS TO BE FULFILLED SINCE EACH PRODUCT
  IS MADE TO ORDER. PLEASE MAKE SURE TO CHECK THE ESTIMATED TURNAROUND
  TIME BEFORE PLACING YOUR ORDER AS CANCELLATIONS WONT BE ELIGIBLE AFTER
  12H FROM PURCHASE.
</p>
<p className={styles.paragraph}>
  FOR ANY MODIFICATION REGARDING SHIPPING ADDRESS PLEASE GET IN TOUCH WITH
  OUR CUSTOMER SERVICE. YOU HAVE 12H AFTER PURCHASE TO DO SO OR IT WILL
  AUTOMATICALLY BE SHIPPED.
</p>
<p className={styles.paragraph}>
  SHIPPING PRICES AND RATES WILL BE CALCULATED AUTOMATICALLY AT CHECKOUT
  BASED ON THE ORDER'S WEIGHT.
</p>
<p className={styles.paragraph}>
  INTERNATIONAL ORDERS MIGHT BE CHARGED IMPORT DUTIES AND TAXES BY CUSTOMS
  UPON ARRIVAL, VELOUR GARMENTS IS NOT RESPONSIBLE FOR ANY OF THEM.
</p>
<p className={styles.paragraph}>
  VELOUR GARMENTS IS NOT RESPONSIBLE FOR ANY LOST OR STOLEN PACKAGES AND
  PACKAGES DAMAGED DURING TRANSIT OR DELIVERY THAT HAVE NOT CONTRACTED OUR
  PACKAGE PROTECTION SERVICE BY ROUTE, PLEASE CONTACT THE COURIER DIRECTLY
  IN ORDER TO SOLVE ANY PROBLEMS THAT MAY ARISE UPON TRANSIT OR DELIVERY.
  IN CASE YOU HAVE CONTRACTED OUR PACKAGE PROTECTION SERVICE, PLEASE GET
  IN TOUCH WITH ROUTE IN ORDER TO SOLVE THE ISSUE, AND THAT INCLUDES
  STOLEN / LOST PACKAGES AND PRODUCTS STAINED OR DAMAGED UPON DELIVERY.
</p>
<p className={styles.paragraph}>
  OUR SHIPPING COURIERS FOR INTERNATIONAL ORDERS ARE DHL, FEDEX AND UPS.
  NATIONAL SHIPMENTS (SPAIN) ARE CARRIED BY MRW.
</p>
<p className={styles.paragraph}>
  IN CASE OF RETURNED PACKAGES DUE TO ANY CIRCUMSTANCES, THE CUSTOMER IS
  RESPONSIBLE FOR THE COST OF RE-SHIPPING.
</p>
<p className={styles.paragraph}>SHIPPING IS NON REFUNDABLE.</p>

<p className={styles.paragraph}>
  FOR ANY UPDATES ON YOUR ORDER / INQUIRES ABOUT SHIPPING PLEASE GET IN
  TOUCH WITH US THROUGH EMAIL.
</p>

<h1 className={styles.heading}>CUSTOMER SERVICE EMAIL</h1>
<p className={styles.paragraph}>SUPPORT@VELOURGARMENTS.COM</p>

<p className={styles.paragraph}>THANK YOU,</p>
<p className={styles.paragraph}>VELOUR GARMENTS</p>
    </div>
    )
*/
}